# Junk

In [8]:
import numpy as np
X = np.random.random((10,5))
y = np.array(['M','M','F','F','M','F','M','M','F','F','F'])
X[X < 0.7] = 0

In [9]:
X

array([[0.76889067, 0.        , 0.76184689, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.99456152, 0.        , 0.78892354, 0.87232346, 0.96527862],
       [0.        , 0.73168093, 0.82207116, 0.        , 0.76920005],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.96663375, 0.        , 0.88741401, 0.81554699],
       [0.98026466, 0.        , 0.98934663, 0.        , 0.71934223],
       [0.71429125, 0.        , 0.        , 0.        , 0.72231386],
       [0.        , 0.76261037, 0.        , 0.84949664, 0.86229983],
       [0.        , 0.84872598, 0.90733287, 0.99959507, 0.        ]])

In [10]:
y

array(['M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'F'], dtype='<U1')

In [11]:
X[X < 0.7]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
from sklearn.svm import SVC

svc = SVC(kernel='linear')

y_pred = svc.predict(np.random((2,5)))

TypeError: 'module' object is not callable

In [14]:
np.random.random((2,5))

array([[0.59886456, 0.51746812, 0.96919051, 0.81062835, 0.04852639],
       [0.26629939, 0.13852772, 0.55239295, 0.24177003, 0.39016755]])

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3) # 1 d to 2d 

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2) # 1 d to 3d 

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3) 

print(newarr)


ValueError: cannot reshape array of size 8 into shape (3,3)